/**
 * Everything `scripts/app-icons.ts` needs to turn `src/shared/appIcon.ts` into files, as pure
 * functions so the test suite can check the plan without touching the repository:
 *
 *  - a rasteriser for the mark on its squircle ground (signed distances, one sample per pixel,
 *    so every size is rendered natively and identically on every machine),
 *  - PNG, ICO and ICNS encoders (PNG-compressed entries; only `node:zlib` is used),
 *  - the Android resources (adaptive-icon layers, colours, the launcher aliases block of the
 *    manifest) and the Kotlin table of alias names.
 */
import { deflateSync, inflateSync } from 'node:zlib'
import {
  APP_ICON_ANDROID,
  APP_ICON_DEFAULT,
  APP_ICON_DESKTOP,
  APP_ICON_INK,
  APP_ICON_MARK,
  APP_ICON_VARIANTS,
  parseHex,
  type AppIconVariant
} from '../../src/shared/appIcon.ts'

export interface OutputFile {
  /** Path relative to the repository root, forward slashes. */
  path: string
  data: Uint8Array | string
}

/** Sizes Electron recommends inside a Windows `.ico` (256 is the largest ICO can hold). */
export const ICO_SIZES = [16, 20, 24, 32, 40, 48, 60, 64, 72, 80, 96, 256] as const

/** macOS icon family: every type a modern `.icns` carries, all PNG-encoded. */
export const ICNS_TYPES: ReadonlyArray<{ type: string; size: number }> = [
  { type: 'icp4', size: 16 },
  { type: 'icp5', size: 32 },
  { type: 'icp6', size: 64 },
  { type: 'ic07', size: 128 },
  { type: 'ic08', size: 256 },
  { type: 'ic09', size: 512 },
  { type: 'ic10', size: 1024 },
  { type: 'ic11', size: 32 },
  { type: 'ic12', size: 64 },
  { type: 'ic13', size: 256 },
  { type: 'ic14', size: 512 }
]

/** Side of the window / Linux icon and of electron-builder's PNG input. */
export const DESKTOP_PNG_SIZE = 512
/** Side of the macOS Dock image (`app.dock.setIcon`). */
export const DOCK_PNG_SIZE = 1024

/** Where the runtime icons of a variant live (relative to the repository root). */
export const RUNTIME_ICON_DIR = 'resources/icons'
export const ANDROID_RES = 'android/app/src/main/res'
export const ANDROID_MANIFEST = 'android/app/src/main/AndroidManifest.xml'
export const KOTLIN_VARIANTS =
  'android/app/src/main/kotlin/app/zen/chromium/LauncherIconVariants.kt'
/** The Kotlin package of the app's sources (the manifest namespace); alias classes live in `.icon`. */
export const ANDROID_NAMESPACE = 'app.zen.chromium'

export const MANIFEST_BEGIN = '<!-- app-icon-aliases:begin'
export const MANIFEST_END = '<!-- app-icon-aliases:end -->'

const GENERATED =
  'Generated by scripts/app-icons.ts from src/shared/appIcon.ts; run `npm run icons` instead of editing.'

// ---------------------------------------------------------------------------
// Raster
// ---------------------------------------------------------------------------

export interface RenderOptions {
  /** Leave the macOS grid margin around the squircle (Dock, Finder and the `.icns`). */
  macInset?: boolean
}

/**
 * The icon at `size` × `size` as straight-alpha RGBA. Coverage comes from signed distances
 * (`0.5 − d` clamped), which gives a clean one-pixel edge at 16 px and at 1024 px alike.
 */
export function renderIcon(
  variant: AppIconVariant,
  size: number,
  opts: RenderOptions = {}
): Uint8Array {
  const out = new Uint8Array(size * size * 4)
  const [fr, fg, fb] = parseHex(variant.fill)
  const [ir, ig, ib] = parseHex(APP_ICON_INK)
  const inset = opts.macInset ? size * APP_ICON_DESKTOP.macInset : 0
  const shape = size - 2 * inset
  const half = shape / 2
  const centre = size / 2
  const r = shape * APP_ICON_DESKTOP.cornerRadius
  const n = APP_ICON_DESKTOP.cornerExponent
  const ringOuter = shape * APP_ICON_DESKTOP.ringOuter
  const ringCentre = ringOuter * APP_ICON_MARK.ring
  const strokeHalf = (ringOuter * APP_ICON_MARK.stroke) / 2
  const dot = ringOuter * APP_ICON_MARK.dot
  const coverage = (d: number): number => Math.min(1, Math.max(0, 0.5 - d))
  for (let py = 0; py < size; py++) {
    for (let px = 0; px < size; px++) {
      const x = px + 0.5 - centre
      const y = py + 0.5 - centre
      // Ground: a rounded box whose corner uses the L^n norm (the squircle).
      const qx = Math.abs(x) - (half - r)
      const qy = Math.abs(y) - (half - r)
      const ground =
        qx > 0 && qy > 0
          ? Math.pow(Math.pow(qx, n) + Math.pow(qy, n), 1 / n) - r
          : Math.max(qx, qy) - r
      const a = coverage(ground)
      const o = (py * size + px) * 4
      if (a <= 0) continue
      const rho = Math.hypot(x, y)
      const mark = Math.min(
        1,
        coverage(Math.abs(rho - ringCentre) - strokeHalf) + coverage(rho - dot)
      )
      out[o] = Math.round(fr + (ir - fr) * mark)
      out[o + 1] = Math.round(fg + (ig - fg) * mark)
      out[o + 2] = Math.round(fb + (ib - fb) * mark)
      out[o + 3] = Math.round(a * 255)
    }
  }
  return out
}

// ---------------------------------------------------------------------------
// PNG
// ---------------------------------------------------------------------------

const CRC_TABLE = (() => {
  const table = new Uint32Array(256)
  for (let i = 0; i < 256; i++) {
    let c = i
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1
    table[i] = c >>> 0
  }
  return table
})()

function crc32(bytes: Uint8Array): number {
  let c = 0xffffffff
  for (const b of bytes) c = CRC_TABLE[(c ^ b) & 0xff] ^ (c >>> 8)
  return (c ^ 0xffffffff) >>> 0
}

function u32(value: number): Uint8Array {
  return new Uint8Array([
    (value >>> 24) & 255,
    (value >>> 16) & 255,
    (value >>> 8) & 255,
    value & 255
  ])
}

function concat(parts: Uint8Array[]): Uint8Array {
  const total = parts.reduce((n, p) => n + p.length, 0)
  const out = new Uint8Array(total)
  let offset = 0
  for (const p of parts) {
    out.set(p, offset)
    offset += p.length
  }
  return out
}

function chunk(type: string, data: Uint8Array): Uint8Array {
  const typeBytes = new TextEncoder().encode(type)
  const body = concat([typeBytes, data])
  return concat([u32(data.length), body, u32(crc32(body))])
}

/** RGBA → PNG (8-bit, colour type 6, filter 0 on every row, maximum deflate). */
export function encodePng(rgba: Uint8Array, size: number): Uint8Array {
  if (rgba.length !== size * size * 4) throw new Error('rgba does not match size')
  const stride = size * 4
  const raw = new Uint8Array((stride + 1) * size)
  for (let y = 0; y < size; y++) {
    raw[y * (stride + 1)] = 0
    raw.set(rgba.subarray(y * stride, (y + 1) * stride), y * (stride + 1) + 1)
  }
  const ihdr = concat([u32(size), u32(size), new Uint8Array([8, 6, 0, 0, 0])])
  return concat([
    new Uint8Array([137, 80, 78, 71, 13, 10, 26, 10]),
    chunk('IHDR', ihdr),
    chunk('IDAT', new Uint8Array(deflateSync(raw, { level: 9 }))),
    chunk('IEND', new Uint8Array(0))
  ])
}

export interface DecodedPng {
  width: number
  height: number
  /** Straight-alpha RGBA (only images written by `encodePng` are understood). */
  rgba: Uint8Array
}

/** Reads back a PNG written by `encodePng` (8-bit RGBA, filter 0) – for the drift test. */
export function decodePng(png: Uint8Array): DecodedPng {
  const view = new DataView(png.buffer, png.byteOffset, png.byteLength)
  let offset = 8
  let width = 0
  let height = 0
  const idat: Uint8Array[] = []
  while (offset < png.length) {
    const length = view.getUint32(offset)
    const type = String.fromCharCode(...png.subarray(offset + 4, offset + 8))
    const data = png.subarray(offset + 8, offset + 8 + length)
    if (type === 'IHDR') {
      width = view.getUint32(offset + 8)
      height = view.getUint32(offset + 12)
      if (png[offset + 16] !== 8 || png[offset + 17] !== 6) throw new Error('not an 8-bit RGBA PNG')
    } else if (type === 'IDAT') {
      idat.push(data)
    }
    offset += 12 + length
  }
  const raw = new Uint8Array(inflateSync(concat(idat)))
  const stride = width * 4
  const rgba = new Uint8Array(stride * height)
  for (let y = 0; y < height; y++) {
    if (raw[y * (stride + 1)] !== 0) throw new Error('unexpected PNG filter')
    rgba.set(raw.subarray(y * (stride + 1) + 1, (y + 1) * (stride + 1)), y * stride)
  }
  return { width, height, rgba }
}

// ---------------------------------------------------------------------------
// ICO and ICNS containers
// ---------------------------------------------------------------------------

export interface IconImage {
  size: number
  png: Uint8Array
}

/** Windows icon: a directory of PNG-compressed images (Vista and later). */
export function encodeIco(images: IconImage[]): Uint8Array {
  const header = new Uint8Array(6)
  const hv = new DataView(header.buffer)
  hv.setUint16(0, 0, true)
  hv.setUint16(2, 1, true)
  hv.setUint16(4, images.length, true)
  const directory = new Uint8Array(16 * images.length)
  const dv = new DataView(directory.buffer)
  let offset = header.length + directory.length
  images.forEach((image, i) => {
    const o = i * 16
    // 256 is stored as 0 (the field is one byte).
    directory[o] = image.size >= 256 ? 0 : image.size
    directory[o + 1] = image.size >= 256 ? 0 : image.size
    directory[o + 2] = 0
    directory[o + 3] = 0
    dv.setUint16(o + 4, 1, true)
    dv.setUint16(o + 6, 32, true)
    dv.setUint32(o + 8, image.png.length, true)
    dv.setUint32(o + 12, offset, true)
    offset += image.png.length
  })
  return concat([header, directory, ...images.map((i) => i.png)])
}

/** The sizes listed in an ICO directory, in order. */
export function icoSizes(ico: Uint8Array): number[] {
  const view = new DataView(ico.buffer, ico.byteOffset, ico.byteLength)
  if (view.getUint16(2, true) !== 1) throw new Error('not an ICO')
  const count = view.getUint16(4, true)
  const sizes: number[] = []
  for (let i = 0; i < count; i++) {
    const w = ico[6 + i * 16]
    sizes.push(w === 0 ? 256 : w)
  }
  return sizes
}

/** macOS icon family: 'icns', total length, then `type` + length + PNG for every entry. */
export function encodeIcns(entries: Array<{ type: string; png: Uint8Array }>): Uint8Array {
  const encoder = new TextEncoder()
  const blocks = entries.map((e) => concat([encoder.encode(e.type), u32(8 + e.png.length), e.png]))
  const total = 8 + blocks.reduce((n, b) => n + b.length, 0)
  return concat([encoder.encode('icns'), u32(total), ...blocks])
}

/** The entry types of an ICNS file, in order. */
export function icnsTypes(icns: Uint8Array): string[] {
  const view = new DataView(icns.buffer, icns.byteOffset, icns.byteLength)
  if (String.fromCharCode(...icns.subarray(0, 4)) !== 'icns') throw new Error('not an ICNS')
  const total = view.getUint32(4)
  if (total !== icns.length) throw new Error('ICNS length mismatch')
  const types: string[] = []
  let offset = 8
  while (offset < total) {
    types.push(String.fromCharCode(...icns.subarray(offset, offset + 4)))
    offset += view.getUint32(offset + 4)
  }
  return types
}

// ---------------------------------------------------------------------------
// Android
// ---------------------------------------------------------------------------

/** `indigo` → `Indigo`: the alias class inside `app.zen.chromium.icon`. */
export function aliasClass(variant: Pick<AppIconVariant, 'id'>): string {
  return `${ANDROID_NAMESPACE}.icon.${variant.id[0].toUpperCase()}${variant.id.slice(1)}`
}

export function androidColorName(variant: Pick<AppIconVariant, 'id'>): string {
  return `ic_launcher_bg_${variant.id}`
}

export function androidMipmapName(variant: Pick<AppIconVariant, 'id'>): string {
  return `ic_launcher_${variant.id}`
}

/** The mark as a vector drawable in the 108 dp adaptive-icon canvas (foreground and monochrome). */
export function androidForegroundXml(): string {
  const { canvas, ringOuter } = APP_ICON_ANDROID
  const c = canvas / 2
  const ring = round(ringOuter * APP_ICON_MARK.ring)
  const stroke = round(ringOuter * APP_ICON_MARK.stroke)
  const dot = round(ringOuter * APP_ICON_MARK.dot)
  const ink = APP_ICON_INK.replace('#', '#FF').toUpperCase()
  // A full circle as an arc that ends a hair from where it starts (an arc back to its own start
  // point is degenerate and disappears).
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- ${GENERATED} -->
<!-- Zenium's mark: a ring with a dot, white; the launcher tints the monochrome copy itself. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="${canvas}dp"
    android:height="${canvas}dp"
    android:viewportWidth="${canvas}"
    android:viewportHeight="${canvas}">
    <path
        android:fillColor="#00000000"
        android:strokeColor="${ink}"
        android:strokeWidth="${stroke}"
        android:pathData="M${c},${round(c - ring)} a${ring},${ring} 0 1,0 0.01,0 Z" />
    <path
        android:fillColor="${ink}"
        android:pathData="M${c},${round(c - dot)} a${dot},${dot} 0 1,0 0.01,0 Z" />
</vector>
`
}

export function androidColorsXml(variants: readonly AppIconVariant[]): string {
  const lines = variants.map(
    (v) => `    <color name="${androidColorName(v)}">${v.fill.toUpperCase()}</color>`
  )
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- ${GENERATED} -->
<resources>
${lines.join('\n')}
</resources>
`
}

export function androidAdaptiveIconXml(variant: AppIconVariant): string {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- ${GENERATED} -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/${androidColorName(variant)}" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
`
}

/**
 * One launcher alias per variant, only the default enabled in the manifest; `LauncherIcon.kt`
 * flips them at runtime. They target `LauncherIconActivity`, which starts `MainActivity` in a
 * task of its own: a task rooted at an alias would be removed the moment that alias is disabled.
 * Deep links, share and search intents stay on `MainActivity` itself.
 */
export function manifestAliasesBlock(
  variants: readonly AppIconVariant[],
  indent = '        '
): string {
  const aliases = variants.map((v) => {
    const relative = aliasClass(v).slice(ANDROID_NAMESPACE.length)
    return `${indent}<activity-alias
${indent}    android:name="${relative}"
${indent}    android:enabled="${v.id === APP_ICON_DEFAULT}"
${indent}    android:exported="true"
${indent}    android:icon="@mipmap/${androidMipmapName(v)}"
${indent}    android:label="@string/app_name"
${indent}    android:targetActivity=".LauncherIconActivity">
${indent}    <intent-filter>
${indent}        <action android:name="android.intent.action.MAIN" />
${indent}        <category android:name="android.intent.category.LAUNCHER" />
${indent}    </intent-filter>
${indent}</activity-alias>`
  })
  return `${indent}${MANIFEST_BEGIN} (${GENERATED}) -->\n${aliases.join('\n')}\n${indent}${MANIFEST_END}`
}

/** The manifest with its aliases block regenerated in place (the markers must exist). */
export function manifestWithAliases(manifest: string, variants: readonly AppIconVariant[]): string {
  const begin = manifest.indexOf(MANIFEST_BEGIN)
  const end = manifest.indexOf(MANIFEST_END)
  if (begin < 0 || end < begin)
    throw new Error(`${ANDROID_MANIFEST} has no app-icon-aliases markers`)
  const lineStart = manifest.lastIndexOf('\n', begin) + 1
  const indent = manifest.slice(lineStart, begin)
  return (
    manifest.slice(0, lineStart) +
    manifestAliasesBlock(variants, indent) +
    manifest.slice(end + MANIFEST_END.length)
  )
}

export function kotlinVariantsSource(variants: readonly AppIconVariant[]): string {
  const entries = variants.map((v) => `        "${v.id}" to "${aliasClass(v)}"`).join(',\n')
  return `// ${GENERATED}
package ${ANDROID_NAMESPACE}

/** The launcher icon variants: id → the \`activity-alias\` that carries that icon. */
object LauncherIconVariants {
    const val DEFAULT = "${APP_ICON_DEFAULT}"

    val ALIASES: Map<String, String> = linkedMapOf(
${entries}
    )
}
`
}

function round(v: number): number {
  return Math.round(v * 100) / 100
}

// ---------------------------------------------------------------------------
// The plan
// ---------------------------------------------------------------------------

export interface PlanInput {
  /** Current text of the Android manifest (its aliases block is regenerated). */
  manifest: string
  variants?: readonly AppIconVariant[]
}

/** Every file the generator writes, for all variants. */
export function planAppIcons(input: PlanInput): OutputFile[] {
  const variants = input.variants ?? APP_ICON_VARIANTS
  const fallback = variants.find((v) => v.id === APP_ICON_DEFAULT) ?? variants[0]
  const files: OutputFile[] = []
  const png = (variant: AppIconVariant, size: number, opts?: RenderOptions): Uint8Array =>
    encodePng(renderIcon(variant, size, opts), size)
  const ico = (variant: AppIconVariant): Uint8Array =>
    encodeIco(ICO_SIZES.map((size) => ({ size, png: png(variant, size) })))

  for (const variant of variants) {
    const dir = `${RUNTIME_ICON_DIR}/${variant.id}`
    files.push({ path: `${dir}/icon.png`, data: png(variant, DESKTOP_PNG_SIZE) })
    files.push({ path: `${dir}/icon.ico`, data: ico(variant) })
    files.push({ path: `${dir}/dock.png`, data: png(variant, DOCK_PNG_SIZE, { macInset: true }) })
    files.push({
      path: `${ANDROID_RES}/mipmap-anydpi-v26/${androidMipmapName(variant)}.xml`,
      data: androidAdaptiveIconXml(variant)
    })
  }

  // electron-builder's inputs: the default variant.
  files.push({ path: 'build/icon.png', data: png(fallback, DESKTOP_PNG_SIZE) })
  files.push({ path: 'build/icon.ico', data: ico(fallback) })
  files.push({
    path: 'build/icon.icns',
    data: encodeIcns(
      ICNS_TYPES.map((e) => ({ type: e.type, png: png(fallback, e.size, { macInset: true }) }))
    )
  })

  // The application icon (Settings → Apps, the installer prompt) is the default variant too.
  files.push({
    path: `${ANDROID_RES}/mipmap-anydpi-v26/ic_launcher.xml`,
    data: androidAdaptiveIconXml(fallback)
  })
  files.push({
    path: `${ANDROID_RES}/drawable/ic_launcher_foreground.xml`,
    data: androidForegroundXml()
  })
  files.push({
    path: `${ANDROID_RES}/values/ic_launcher_colors.xml`,
    data: androidColorsXml(variants)
  })
  files.push({ path: ANDROID_MANIFEST, data: manifestWithAliases(input.manifest, variants) })
  files.push({ path: KOTLIN_VARIANTS, data: kotlinVariantsSource(variants) })
  return files
}
