// Generated by scripts/app-icons.ts from src/shared/appIcon.ts; run `npm run icons` instead of editing.
package app.zen.chromium

/** The launcher icon variants: id → the `activity-alias` that carries that icon. */
object LauncherIconVariants {
    const val DEFAULT = "indigo"

    val ALIASES: Map<String, String> = linkedMapOf(
        "indigo" to "app.zen.chromium.icon.Indigo",
        "purple" to "app.zen.chromium.icon.Purple",
        "ocean" to "app.zen.chromium.icon.Ocean",
        "forest" to "app.zen.chromium.icon.Forest",
        "sunset" to "app.zen.chromium.icon.Sunset",
        "rose" to "app.zen.chromium.icon.Rose",
        "slate" to "app.zen.chromium.icon.Slate",
        "graphite" to "app.zen.chromium.icon.Graphite"
    )
}
