package app.zen.chromium

/**
 * GENERATED by `scripts/v2-tokens-kotlin.ts` from `src/renderer/src/assets/main.css` – do not edit;
 * run `node --experimental-strip-types --no-warnings scripts/v2-tokens-kotlin.ts` after the CSS.
 *
 * The design language v2 inks a native Android view draws with, as the chrome's stylesheet
 * declares them (the token block's `:root` and `:root[data-theme='dark']`), for the one chrome
 * surface the app imitates natively: the page-unresponsive prompt ([UnresponsivePrompt], v2
 * §9.23), raised while the renderer the chrome shares is hung. `v2-tokens-kotlin.test.ts` fails
 * when this file is stale against the CSS; `V2TokensTest` parses the CSS on the JVM and fails
 * when the two disagree, so no value here can drift from the sheet the chrome draws.
 */
object V2Tokens {
    /** One theme's inks, ARGB. */
    class Theme(
        /** `--v2-panel`: a panel, sheet or menu's fill. */
        val panel: Int,
        /** `--v2-border`: the 1 px hairline. */
        val border: Int,
        /** `--v2-text`. */
        val text: Int,
        /** `--v2-text-deemphasized`: the text at 69 %. */
        val textDeemphasized: Int,
        /** `--v2-fill`: the text at 10 %, a control's fill at rest. */
        val fill: Int,
        /** `--v2-fill-hover`: the text at 16 %, the control under a hover or a press. */
        val fillHover: Int,
        /** `--v2-scrim`: black at [scrimAlpha]. */
        val scrim: Int,
        /** `--v2-danger` (the chrome's `--zen-danger`): the destructive ink. */
        val danger: Int,
        /** `--zen-scrim-alpha`: the window's dim behind a sheet. */
        val scrimAlpha: Float
    )

    val light = Theme(
        panel = 0xFFF4F4F4.toInt(),
        border = 0x26000000.toInt(),
        text = 0xFF15141A.toInt(),
        textDeemphasized = 0xB015141A.toInt(),
        fill = 0x1A15141A.toInt(),
        fillHover = 0x2915141A.toInt(),
        scrim = 0x66000000.toInt(),
        danger = 0xFFC43434.toInt(),
        scrimAlpha = 0.4f
    )

    val dark = Theme(
        panel = 0xFF1F1F1F.toInt(),
        border = 0x1FFFFFFF.toInt(),
        text = 0xFFFBFBFE.toInt(),
        textDeemphasized = 0xB0FBFBFE.toInt(),
        fill = 0x1AFBFBFE.toInt(),
        fillHover = 0x29FBFBFE.toInt(),
        scrim = 0x8C000000.toInt(),
        danger = 0xFFFF8080.toInt(),
        scrimAlpha = 0.55f
    )

    /** `.zen-sheet-handle`: the grabber's alpha on [Theme.text]. */
    const val HANDLE_ALPHA = 0.25f

    fun of(dark: Boolean): Theme = if (dark) this.dark else light
}
